version: '3'

services:

  cadastro-anuncio:
    build:
      dockerfile: dockerfile
      context: .
    image: raphael/cadastro-anuncio
    restart: on-failure
    container_name: cadastro-anuncio
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - BANCO_URL=jdbc:mysql://mysql:3306/anuncio_db?allowPublicKeyRetrieval=true&sslMode=DISABLED

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=anuncio_db
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: