server:
  port: 8080

spring:
  application:
    name: cadastro-anuncio
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${BANCO_URL:jdbc:mysql://localhost:3306/anuncios_db?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: root
    password: 123456
